idle_bg = "#1e1e2e" 
idle_fg = "#cdd6f4" 
info_bg = "#1e1e2e" 
info_fg = "#89b4fa" 
good_bg = "#74c7ec"
good_fg = "#181825"
warning_bg = "#ebcb8b"
warning_fg = "#2e3440"
critical_bg = "#f38ba8"
critical_fg = "#181825"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
